// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQRLKwjUJkB56nkxgt1iiIMNrJrxc2oVU',
    appId: '1:142895664694:android:b277e07579d8e14e305297',
    messagingSenderId: '142895664694',
    projectId: 'expenses-app-e9064',
    databaseURL: 'https://expenses-app-e9064-default-rtdb.firebaseio.com',
    storageBucket: 'expenses-app-e9064.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ry4VS9P5aybHvm416DEW6VEWprRA76g',
    appId: '1:142895664694:ios:e6e7cbb66fe48fb1305297',
    messagingSenderId: '142895664694',
    projectId: 'expenses-app-e9064',
    databaseURL: 'https://expenses-app-e9064-default-rtdb.firebaseio.com',
    storageBucket: 'expenses-app-e9064.appspot.com',
    iosClientId: '142895664694-klfem68m5bmomm1svu2g9l3q1sqdcbe1.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalExpensesTracker',
  );
}
